language: java

jdk:
  - oraclejdk8

sudo: false
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# cache between builds
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  email: false